export const ACTION_SCHEMA_COPY = Object.freeze({
  submitAction: '提交本次 Agent 轮次唯一的下一项动作。',
  root: '为当前 Run 阶段选择且只选择一项有效动作。响应对象必须且只能包含 action 字段。',
  actionEnvelope: '具体动作对象。finish 的完整外形是 {"action":{"kind":"finish","summary":"...","acceptanceEvidence":[],"diff":null}}。',
  inspect: '在检查阶段读取相关项目上下文。',
  tool: '执行当前阶段允许的下一项具体操作或只读取证操作。',
  verify: '使用精确命令运行一个已配置的验证项。',
  verificationCheckId: '本次请求精确执行的已配置验证项 id。',
  requestId: '本 Run 内唯一且稳定的请求标识。',
  plan: '建立当前执行计划，或对其进行实质修订。',
  planId: '稳定的计划标识；修订同一计划时必须复用。',
  planSummary: '聚焦后续有效步骤的简洁有序计划。',
  planRationale: '说明该计划为什么符合目标、验收标准、约束和当前证据。',
  planSteps: '当前 Run 的可执行清单，按依赖关系列出检查、修改和验证步骤。',
  workItemId: '本计划内稳定且唯一的清单项 id。',
  workItemTitle: '清晰、可验证的一项工作。',
  workItemKind: '清单项类型：inspect、change 或 verify。',
  workItemDependencies: '必须先完成的清单项 id；无依赖时返回空数组。',
  workItemReference: '本动作正在推进的 checklist item id；检查阶段尚无清单时设为 null。',
  diffRequestId: '成功 git_diff 工具结果的请求 id。',
  finish: '结束当前 Run。此对象是外层 action 字段的值，不要在这里再次添加 action 包装。',
  completionSummary: '以已记录证据为依据的简洁完成结果。',
  criterionId: '来自 Run 事实 acceptanceCriteria 的验收标准 id。',
  criterionSummary: '说明引用的证据如何满足该验收标准。',
  evidenceRefs: '逐字复制自 Run 事实 successfulEvidenceRefs 的 id；不得把验收标准 id 当作证据引用。',
  blocked: '只有存在无法用当前工具或证据解决的真实阻塞时才能停止。',
  blockedSummary: '简洁的阻塞摘要。',
  blockedReason: '阻止继续推进的外部输入、不可用能力或目标冲突。',
})
